version: "3.8"

x-common-backend: &common-backend
  build:
    context: .
    dockerfile: Dockerfile
  image: stenagrafist_backend
  networks:
    - stenagrafist
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  consumer:
    <<: *common-backend
    container_name: consumer
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8012:8000
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app/
  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch:8.11.1
    ports:
      - '${ELASTIC_PORT}:9200'
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 1s
      retries: 100
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  stenagrafist:
    external: True